"""Event names used in process-case audit history."""

from enum import StrEnum


class EventType(StrEnum):
    LEAD_INTAKE_RECEIVED = "LEAD_INTAKE_RECEIVED"
    INTENT_EXTRACTED = "INTENT_EXTRACTED"
    QUALIFICATION_EVALUATED = "QUALIFICATION_EVALUATED"
    CUSTOMER_RESPONSE_CREATED = "CUSTOMER_RESPONSE_CREATED"
    TRIGGER_RECEIVED = "TRIGGER_RECEIVED"
    DECISION_RECORDED = "DECISION_RECORDED"
    STATE_CHANGED = "STATE_CHANGED"
    TRANSITION_REJECTED = "TRANSITION_REJECTED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
