"""Event names used in process-case audit history."""

from enum import StrEnum


class EventType(StrEnum):
    LEAD_INTAKE_RECEIVED = "LEAD_INTAKE_RECEIVED"
    INTENT_EXTRACTED = "INTENT_EXTRACTED"
    QUALIFICATION_EVALUATED = "QUALIFICATION_EVALUATED"
    CUSTOMER_RESPONSE_CREATED = "CUSTOMER_RESPONSE_CREATED"
    TRIGGER_RECEIVED = "TRIGGER_RECEIVED"
    DECISION_RECORDED = "DECISION_RECORDED"
    STATE_CHANGED = "STATE_CHANGED"
    TRANSITION_REJECTED = "TRANSITION_REJECTED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    COMMERCIAL_PATH_SELECTED = "COMMERCIAL_PATH_SELECTED"
    AVAILABILITY_CALCULATED = "AVAILABILITY_CALCULATED"
    SLOTS_PROPOSED = "SLOTS_PROPOSED"
    SLOT_SELECTED = "SLOT_SELECTED"
    BOOKING_CREATED = "BOOKING_CREATED"
    BOOKING_CANCELLED = "BOOKING_CANCELLED"
    BOOKING_RESCHEDULED = "BOOKING_RESCHEDULED"
    PRICING_INPUT_RECORDED = "PRICING_INPUT_RECORDED"
    QUOTE_CALCULATED = "QUOTE_CALCULATED"
    QUOTE_PRESENTED = "QUOTE_PRESENTED"
    QUOTE_ACCEPTED = "QUOTE_ACCEPTED"
    QUOTE_REJECTED = "QUOTE_REJECTED"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    PAYMENT_REQUEST_CREATED = "PAYMENT_REQUEST_CREATED"
    PAYMENT_REQUEST_EXPIRED = "PAYMENT_REQUEST_EXPIRED"
    HUMAN_REPLY_SENT = "HUMAN_REPLY_SENT"
    # Proactive re-contact of a stalled lead (universal-sales-cycle-model.md
    # section 8) -- recorded by PersistentFollowUpRunner, never by the
    # reactive LeadIntakeService.receive() path.
    FOLLOW_UP_SENT = "FOLLOW_UP_SENT"
