"""Audit event names for Demand campaigns and prospects."""

from enum import StrEnum


class CampaignEventType(StrEnum):
    TRIGGER_RECEIVED = "TRIGGER_RECEIVED"
    DECISION_RECORDED = "DECISION_RECORDED"
    STATE_CHANGED = "STATE_CHANGED"
    TRANSITION_REJECTED = "TRANSITION_REJECTED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    MARKETING_DNA_COMPILED = "MARKETING_DNA_COMPILED"
    ASSETS_COMPILED = "ASSETS_COMPILED"
    CAMPAIGN_APPROVED = "CAMPAIGN_APPROVED"


class ProspectEventType(StrEnum):
    TRIGGER_RECEIVED = "TRIGGER_RECEIVED"
    DECISION_RECORDED = "DECISION_RECORDED"
    STATE_CHANGED = "STATE_CHANGED"
    TRANSITION_REJECTED = "TRANSITION_REJECTED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    CONTENT_VIEWED = "CONTENT_VIEWED"
    CONTENT_ENGAGED = "CONTENT_ENGAGED"
    OPT_IN_RECORDED = "OPT_IN_RECORDED"
    SEQUENCE_STEP_SENT = "SEQUENCE_STEP_SENT"
    SEQUENCE_STEP_OPENED = "SEQUENCE_STEP_OPENED"
    CTA_CLICKED = "CTA_CLICKED"
    INQUIRY_RECEIVED = "INQUIRY_RECEIVED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    NURTURE_EXHAUSTED = "NURTURE_EXHAUSTED"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    SEND_BLOCKED = "SEND_BLOCKED"
